# Generated by Django 5.1.2 on 2024-11-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='wager',
            name='match',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='end_date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='wager',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='wager',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wager',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='wager',
            name='user',
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wager',
            name='game',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wager',
            name='players',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wager',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gameapp.game')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
