# Generated by Django 5.1.2 on 2024-11-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_game_remove_message_room_remove_match_player1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('players', models.CharField(max_length=10)),
                ('current_players', models.IntegerField(default=0)),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/images/')),
            ],
        ),
    ]
