# Generated by Django 5.1.2 on 2024-11-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_remove_player_game_player_game_id_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='game',
        ),
    ]
