# Generated by Django 5.1.2 on 2024-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_rename_game_id_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
