# Generated by Django 5.1.2 on 2024-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0007_alter_player_points_alter_player_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
