# Generated by Django 5.1.2 on 2024-11-06 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_player_last_active_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wager',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wager',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wager',
            name='game',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wager',
            name='players',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='wager',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
    ]
